---
abstract: 'Plack Server implementation that uses HTTP::Server::Simple'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Server-ServerSimple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  HTTP::Server::Simple: 0.41
  HTTP::Status: 0
  Plack::Util: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Server-ServerSimple.git
version: 0.03
